# Checkpoint 0

These exercises are a mix of Python and Pandas practice. Most should be no more than a few lines of code!

In [ ]:
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]

In [ ]:
# get a list containing the last 3 elements of a
# Yes, you can just type out [4, 5, 6] but we really want to see you demonstrate you know how to use list slicing in Python
listb = a[3:5]

In [ ]:
# create a list of numbers from 1 to 20
lista = []
for x in range(21):
    lista.append(x)

In [ ]:
# now get a list with only the even numbers between 1 and 100
# you may or may not make use of the list you made in the last cell
list even = []
for x in range(1,101):
    if (x%2) == 0:
        even.append(x)

In [ ]:
# write a function that takes two numbers as arguments
# and returns the first number divided by the second
def divide(x,y):
    return (x/y)

In [ ]:
# write a function that takes a string as input
# and return that string in all caps
def cap(string):
    return string.upper()

In [ ]:
# fizzbuzz
# you will need to use both iteration and control flow 
# go through all numbers from 1 to 30 in order
# if the number is a multiple of 3, print fizz
# if the number is a multiple of 5, print buzz
# if the number is a multiple of 3 and 5, print fizzbuzz and NOTHING ELSE
# if the number is neither a multiple of 3 nor a multiple of 5, print the number
for x in range(1,30):
    if x%3 == 0 and x%5 != 0:
        print(fizz)
    elif x%3 !=0 and x%5 == 0:
        print(buzz)
    elif x%3==0 and x%5==0:
        print(fizzbuzz)
    else:
        print x;

In [2]:
# create a dictionary that reflects the following menu pricing (taken from Ahmo's)
# Gyro: $9 
# Burger: $9
# Greek Salad: $8
# Philly Steak: $10
prices = {"Gyro":9, "Burger":9, "Greek Salad":8, "Philly Steak": 10}

In [6]:
# load in the "starbucks.csv" dataset
# refer to how we read the cereal.csv dataset in the tutorial
import pandas as pd
df = pd.read_csv("../data/starbucks.csv")
type(df)

pandas.core.frame.DataFrame

In [18]:
# output the calories, sugars, and protein columns only of every 40th row. 
df.iloc[::40]
df_.loc["calories", "sugars","protein"]

NameError: name 'df_' is not defined

In [19]:
# select all rows with more than and including 400 calories
df["calores"] > 400

KeyError: 'calores'

In [20]:
# select all rows whose vitamin c content is higher than the iron content
df[df["vitamin c"] > df["sugars"]]

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine
175,smoothies,orange mango banana smoothie,Grande Nonfat Milk,260,1.0,0.3,0.0,5,120,54,6,37,16.0,50,80,10,30.0,15.0
176,smoothies,orange mango banana smoothie,2% Milk,270,1.5,0.5,0.0,5,125,53,6,37,16.0,50,80,10,6.0,0.0
177,smoothies,orange mango banana smoothie,Soymilk,270,1.5,0.4,0.0,5,120,53,6,36,15.0,50,80,10,6.0,0.0
178,smoothies,strawberry banana smoothie,Grande Nonfat Milk,290,1.0,0.3,0.0,5,125,58,7,41,16.0,4,100,10,8.0,0.0
179,smoothies,strawberry banana smoothie,2% Milk,290,2.0,1.0,0.0,5,125,58,7,41,16.0,4,100,10,8.0,0.0
180,smoothies,strawberry banana smoothie,Soymilk,290,2.0,0.4,0.0,5,120,58,8,40,16.0,2,100,10,8.0,0.0

In [26]:
# create a new column containing the caffeine per calories of each drink
df["caffeine per calories"] = df["caffeine"] / df["calories"]
df.head()

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine,caffeine per calories
0,coffee,brewed coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0,0,0,0.0,175.0,58.333333
1,coffee,brewed coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0,0,0,0.0,260.0,65.000000
2,coffee,brewed coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,0,0.0,330.0,66.000000
3,coffee,brewed coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,2,0.0,410.0,82.000000
4,classic espresso drinks,caff latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10,0,20,0.0,75.0,1.071429

In [27]:
# what is the average calorie across all items?
df["caffeine per calories"].mean()
df.head()

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine,caffeine per calories
0,coffee,brewed coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0,0,0,0.0,175.0,58.333333
1,coffee,brewed coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0,0,0,0.0,260.0,65.000000
2,coffee,brewed coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,0,0.0,330.0,66.000000
3,coffee,brewed coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,2,0.0,410.0,82.000000
4,classic espresso drinks,caff latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10,0,20,0.0,75.0,1.071429

In [28]:
# how many different categories of beverages are there?
print(df["beverage"].unique())

['brewed coffee' 'caff latte' 'caff mocha (without whipped cream)'
 'vanilla latte (or other flavoured latte)' 'caff americano' 'cappuccino'
 'espresso' 'skinny latte (any flavour)' 'caramel macchiato'
 'white chocolate mocha (without whipped cream)'
 'hot chocolate (without whipped cream)'
 'caramel apple spice (without whipped cream)' 'tazo tea'
 'tazo chai tea latte' 'tazo green tea latte' 'tazo fullleaf tea latte'
 'tazo fullleaf red tea latte (vanilla rooibos)'
 'iced brewed coffee (with classic syrup)'
 'iced brewed coffee (with milk  classic syrup)'
 'shaken iced tazo tea (with classic syrup)'
 'shaken iced tazo tea lemonade (with classic syrup)'
 'banana chocolate smoothie' 'orange mango banana smoothie'
 'strawberry banana smoothie' 'coffee' 'mocha (without whipped cream)'
 'caramel (without whipped cream)' 'java chip (without whipped cream)'
 'mocha' 'caramel' 'java chip'
 'strawberries  crme (without whipped cream)'
 'vanilla bean (without whipped cream)']

In [ ]:
# what is the average # calories for each beverage category?
beverages = df.groupby("beverage")
beverages["calories"].mean()

In [ ]:
# plot the distribution of the number of calories in drinks with a histogram
df["calories"].plot.hist(edgecolor='black', alpha=0.8, title="the number of calories in drinks")

In [ ]:
# plot calories against total fat with a scatterplot
df.plot.scatter(x="calories", y="fat", title="calories against total fat")